### ISSUE TITLE
Release Drafter - Your helper to almost creating a release

### ISSUE THREAD

**Issue by arunpoudel** [coopnorge/demos#49]
```[tasklist]
### Tasks
- [x] Prepare a basic slide
- [x] Prepare a repo with go project
- [x] Prepare PRs with various change
- [x] Practice Presentation
```
